#Hugo configuration
title = "asdewrdsf"
baseURL = "https:\/\/werdf.cxgefrt.wer"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
